{"uuid": "41533db6-b717-4084-b860-92ab7215393b", "children": ["f288ea9f-c404-438c-8d43-9459d5741db2"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '/home/vladimir/Develop/final_project_duo/tests/logs/test_login_and_logout_old_account.log'\n", "trace": "  File \"/home/vladimir/Develop/final_project_duo/venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/vladimir/Develop/final_project_duo/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/vladimir/Develop/final_project_duo/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/vladimir/Develop/final_project_duo/conftest.py\", line 40, in browser\n    file_handler = logging.FileHandler(f\"logs/{request.node.name}.log\")\n  File \"/usr/lib/python3.8/logging/__init__.py\", line 1147, in __init__\n    StreamHandler.__init__(self, self._open())\n  File \"/usr/lib/python3.8/logging/__init__.py\", line 1176, in _open\n    return open(self.baseFilename, self.mode, encoding=self.encoding)\n"}, "start": 1661094275673, "stop": 1661094275673}], "start": 1661094275673, "stop": 1661094275769}